name: CI - Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: course/package-lock.json

    - name: Install Dependencies
      run: npm ci
      working-directory: course

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        working-directory: course
        build: npm run build
        start: npm run dev
        wait-on: 'http://localhost:5173'
        spec: cypress/e2e/booking.cy.ts,cypress/e2e/reserv_1.cy.js

